create table country
(
    id bigint generated by default as identity
        primary key,
    name varchar(255),
    continent varchar(255)
);

create table guest
(
    id bigint generated by default as identity
        primary key,
    name varchar(255),
    surname varchar(255),
    country_id bigint references country
);

create table host
(
    id bigint generated by default as identity
        primary key,
    name varchar(255),
    surname varchar(255),
    country_id bigint references country
);

create table hosts_guests
(
    host_id bigint references host,
    guest_id bigint references guest,
    primary key (host_id, guest_id)
);

create table accommodation
(
    id bigint generated by default as identity
        primary key,
    name varchar(255),
    category varchar(20),
    host_id bigint references host,
    num_rooms integer,
    is_rented boolean default false
);

create table users
(
    username varchar(255)
        primary key,
    password varchar(255),
    name varchar(255),
    surname varchar(255),
    is_account_non_expired boolean default true,
    is_account_non_locked boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled boolean default true,
    role varchar(50)
);

create table temporary_reservation
(
    id bigint generated by default as identity
        primary key,
    date_created timestamp,
    user_username varchar(255) references users,
    status varchar(50)
);

create table accommodations_temp_reservations
(
    accommodation_id bigint references accommodation,
    temporary_reservation_id bigint references temporary_reservation,
    primary key (accommodation_id, temporary_reservation_id)
);

-- create index idx_cart_user_status on shopping_cart (user_username, status);
-- create index idx_user_username_password on shop_users (username, password);
-- create index idx_user_username on shop_users (username);
-- create index idx_user_role on shop_users (role);
